services:
  postgres:
    #   Restarts unless it's manually stopped.
    restart: unless-stopped
    #   Use the Docker Image postgres. This will pull the latest release.
    image: postgres
    #   Give the container the name hr_postgres to be easily identified when running.
    container_name: fishing_the_net
    #   Setup the environment of the container.
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=fishing_the_net
    #   Maps port 5432 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - 5434:5432
    #   Set a volume so the database is not lost after shutting down the container.
    #   TEMPORARY SOLUTION: To run this docker file on WINDOWS, please comment the below 2 lines.
    volumes:
      - ./data:/var/lib/postgresql/data