FROM openjdk:17

COPY target/fishing-the-net-0.0.1-SNAPSHOT.jar target/fishing-the-net-0.0.1-SNAPSHOT.jar
COPY src/main/resources/ src/main/resources/

ENTRYPOINT java -jar /target/fishing-the-net-0.0.1-SNAPSHOT.jar